new

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,3 +1,13 @@
 #!/bin/bash
+if [ -z "$PYFILE" ]
+	then
+		echo "PYFILE is not set"
+		exit 1
+fi
+if [ ! -f "$PYFILE" ]
+	then
+		echo "Error: Python file '$PYFILE' not found."
+		exit 1
+fi
+echo "Compiling $PYFILE ..."
 python3 -m compileall -b "$PYFILE"
-
